# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ffa7bb8989ed947b5e9742aed072056cae5e3f9e7c16189799b6964f985fac51d30c998fcdc3ea09d3cb09610258ad638a61d28255d7958d816dd045f40d3efe

test:
  secret_key_base: 4d3c468ca1b63771df2d113caced8692fa4fe798ddc9db2b1fd14d501f924cc7ed64b15c017d1395747acd398a446d52bdc4a6a46c670669ac6fe12858bff0ab

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
